### PR TITLE
Added unit tests for basic usage.

### PR DESCRIPTION
**Pull request by huogerac**
Hi this is an attempt to add an initial unit test for your project.
- TOX tests agains Python 2 and 3
- PyTests behind the scenes
- The tests can be used to understand the library usage (live documentation)

How to test?
tox

### CODE REVIEW

**Comment by AzMoo** [comment]
Thanks so much for your contribution @huogerac 

The only thing I would ask is that you install and run pre-commit to fix the code style (line endings, length of lines, etc.) and then I'll accept the pull request.

**Comment by luzfcb** [comment]
LGTM

**Comment by huogerac** [comment]
Hi @AzMoo,
Not sure the correct process, but I did another PR.
Check it up please
https://github.com/AzMoo/python-decouple-aws/pull/3

**Comment by AzMoo** [comment]
Thanks @huogerac 

Last change we need to make is to drop the requirements-dev.txt and move those dev requirements into the pyproject.toml file.

This project uses the pyproject.toml format and the poetry tool to handle dependencies and building (https://poetry.eustace.io/docs/pyproject/). This is probably a little different to what you're used to, but we've opted for this new packaging method to simplify the building and deployment process.

**Comment by huogerac** [comment]
Done! I hope all good now

**Comment by AzMoo** [comment]
That's great @huogerac Thanks so much for your contribution.

**Pull request merged**
